server {
  listen 80;
  server_name localhost;

  root /usr/share/nginx/html;
  index index.html;

  # React Router maneja rutas como /dashboard, /proyectos y /recursos.
  # Si Nginx no encuentra un archivo real, devuelve index.html.
  location / {
    try_files $uri /index.html;
  }
}
